image_width: 1920
image_height: 1200
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1148.0427 ,    0.     ,  960.21916,
            0.     , 1147.50364,  595.77837,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.000319, -0.000510, 0.000185, -0.000246, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1147.51465,    0.     ,  959.08877,    0.     ,
            0.     , 1146.93518,  595.54456,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
